### PR TITLE
Add variations with "Rep." at the end

### PR DESCRIPTION
**Pull request by jcushman**
This PR adds a bunch of variations with an existing reporter string plus "Rep." The process was to look at CAP's [spreadsheet](https://docs.google.com/spreadsheets/d/1TsxGPpzGKKFLq8isLr_l9Zr_HfwyRsOram2sN7GPjz8/edit#gid=0) of cite-like strings, and find all strings where the reporter name would be valid if "Rep." was removed.

(A side effect of injecting these new values was to alphabetize all of the `"variations"` dicts, so there are a few instances in the diff where the dict is alphabetized but otherwise unchanged. I kept that behavior because keeping the dicts alphabetized seemed like a good idea anyway, to reduce future typos. Alphabetization could be added to the tests potentially.)

reporters-db already had the high-frequency "Rep." variations, so this covers the lower-frequency ones. In total these changes capture close to 40,000 new cites in CAP's collection. Here's the frequency counts for posterity:

`[(3727, 'John. Rep.'), (3502, 'N. Y. Rep.'), (3172, 'Conn. Rep.'), (2288, 'Johns. Ch. Rep.'), (1886, 'Ohio Rep.'), (1351, 'Mo. Rep.'), (1201, 'Wend. Rep.'), (1028, 'Pick. Rep.'), (878, 'Ohio St. Rep.'), (751, 'Wheat. Rep.'), (696, 'Ark. Rep.'), (656, 'Wash. C. C. Rep.'), (551, 'How. Pr. Rep.'), (548, 'Cow. Rep.'), (531, 'Vt. Rep.'), (454, 'La. Rep.'), (430, 'Texas Rep.'), (423, 'Maine Rep.'), (422, 'Dev. Rep.'), (418, 'Pet. Rep.'), (371, 'Ga. Rep.'), (337, 'Tex. Rep.'), (334, 'How. Rep.'), (309, 'U. S. Rep.'), (309, 'At. Rep.'), (303, 'Black. Rep.'), (279, 'Wash. Rep.'), (274, 'Yerg. Rep.'), (269, 'Verm. Rep.'), (267, 'Cal. Rep.'), (258, 'Harr. Rep.'), (246, 'Stew. Rep.'), (244, 'S. Ct. Rep.'), (242, 'Litt. Rep.'), (239, 'Miss. Rep.'), (234, 'Barb. Ch. Rep.'), (212, 'Tenn. Rep.'), (203, 'Ired. Rep.'), (184, 'Yer. Rep.'), (175, 'Dall. Rep.'), (173, 'Phil. Rep.'), (171, 'Phila. Rep.'), (169, 'Rand. Rep.'), (169, 'N.W. Rep.'), (168, 'Munf. Rep.'), (160, 'Hay. Rep.'), (158, 'Okla. Crim. Rep.'), (140, 'Binn. Rep.'), (137, 'Blackf. Rep.'), (132, 'Edw. Ch. Rep.'), (124, 'Peters Rep.'), (123, 'Desaus. Rep.'), (119, 'Pa. Co. Ct. Rep.'), (114, 'Del. Co. Rep.'), (110, 'Caines Rep.'), (110, 'Aik. Rep.'), (109, 'Port. Rep.'), (103, 'Pacific Rep.'), (101, 'Parker Cr. Rep.'), (99, 'All. Rep.'), (94, 'Dev. Eq. Rep.'), (94, 'Const. Rep.'), (91, 'Hayw. Rep.'), (90, 'Marsh. Rep.'), (89, 'Met. Rep.'), (86, 'Md. Rep.'), (86, 'Barb. Rep.'), (85, 'Paige Ch. Rep.'), (82, 'La. Ann. Rep.'), (80, 'Rob. Rep.'), (78, 'S.W. Rep.'), (78, 'Paige Rep.'), (76, 'Bin. Rep.'), (75, 'Misc.Rep.'), (75, 'Ill. Rep.'), (74, 'Humph. Rep.'), (73, 'Whart. Rep.'), (72, 'W. Rep.'), (70, 'Murph. Rep.'), (69, 'Ten. Rep.'), (65, 'Okla. Cr. Rep.'), (64, 'Cranch Rep.'), (63, 'Johnson Rep.'), (61, 'Mon. Rep.'), (61, 'Ired. Eq. Rep.'), (60, 'J. Rep.'), (59, 'Metc. Rep.'), (58, 'Gall. Rep.'), (57, 'Brock. Rep.'), (56, 'Hill Rep.'), (55, 'Bur. Rep.'), (53, 'Wis. Rep.'), (53, 'Ter. Rep.'), (50, 'Sand. Ch. Rep.'), (48, 'Lit. Rep.'), (44, 'S.E. Rep.'), (44, 'Mis. Rep.'), (43, 'Brev. Rep.'), (43, 'Bibb Rep.'), (41, 'Ohio Dec. Rep.'), (41, 'L. Rep.'), (39, 'Ky. Rep.'), (39, 'Dana Rep.'), (38, 'Story Rep.'), (38, 'Okla. Rep.'), (37, 'Mart. Rep.'), (36, 'Dallas Rep.'), (35, 'D. Chip. Rep.'), (35, 'App. Div. Rep.'), (32, 'Ohio Dec.Rep.'), (32, 'Mich. Rep.'), (31, 'Scam. Rep.'), (31, 'Cal.Rep.'), (30, 'Bail. Rep.'), (29, 'Min. Rep.'), (29, 'Howard Rep.'), (29, 'Hill Ch. Rep.'), (29, 'Hawks Rep.'), (29, 'Edw. Rep.'), (29, 'Doug. Rep.'), (29, 'Dal. Rep.'), (29, 'Chip. Rep.'), (29, 'Cain. Rep.'), (29, 'App. Rep.'), (28, 'Va. Rep.'), (28, 'S.W.Rep.'), (28, 'Minn. Rep.'), (27, 'Maryland Rep.'), (26, 'Watts Rep.'), (26, 'O. Rep.'), (25, 'Wendell Rep.'), (25, 'South.Rep.'), (25, 'Hoff. Ch. Rep.'), (25, 'Denio Rep.'), (24, 'Rich. Rep.'), (24, 'Porter Rep.'), (24, 'N. W.Rep.'), (24, 'Des. Rep.'), (23, 'Sandf. Rep.'), (23, 'Hum. Rep.'), (22, 'Iowa Rep.'), (22, 'Ill. App. Rep.'), (22, 'B. Mon. Rep.'), (21, 'Phil.Rep.'), (21, 'Leg. Gaz. Rep.'), (20, 'N.H. Rep.'), (20, 'Atl.Rep.'), (19, 'Sumn. Rep.'), (19, 'Mas. Rep.'), (19, 'Cush. Rep.'), (18, 'N.W.Rep.'), (18, 'Ct. Cl. Rep.'), (18, 'Black Rep.'), (17, 'Wheaton Rep.'), (16, 'Rich. Eq. Rep.'), (16, 'Rawle Rep.'), (16, 'P. Rep.'), (16, 'Luz. Leg. Reg. Rep.'), (16, 'Hopk. Ch. Rep.'), (15, 'Leigh Rep.'), (15, 'H. Rep.'), (15, 'Call Rep.'), (14, 'Wilson Rep.'), (14, 'Ohio App. Rep.'), (14, 'McCord Rep.'), (14, 'Ired. Law Rep.'), (14, 'Haw. Rep.'), (14, 'C. C. A. Rep.'), (14, 'Abb. Rep.'), (13, 'Tex.Rep.'), (13, 'Phill. Rep.'), (13, 'Mur. Rep.'), (13, 'Martin Rep.'), (13, 'John.Rep.'), (13, 'Del.Co.Rep.'), (13, 'Del. Rep.'), (13, 'Bailey Rep.'), (12, 'Sto. Rep.'), (12, 'S.E.Rep.'), (12, 'Mass.Rep.'), (12, 'Mar. Rep.'), (12, 'Florida Rep.'), (12, 'Fla. Rep.'), (12, 'Del. Ch. Rep.'), (12, 'Cal. App. Rep.'), (11, 'Yeates Rep.'), (11, 'Whar. Rep.'), (11, 'S.Ct.Rep.'), (11, 'S. E.Rep.'), (11, 'Ala.Rep.'), (10, 'Wh. Rep.'), (10, 'Wash. Co. Rep.'), (10, 'S. W.Rep.'), (10, 'McCord Ch. Rep.'), (10, 'Littell Rep.'), (10, 'Kan. Rep.')]`

### CODE REVIEW

**Comment by mlissner** [comment]
Wow, wow, wow. LGTM. Merging. Are you going to need a release soon?

**Comment by mlissner** [comment]
I'm +1 on an "are things alphabetized" test, but only if it checks all the keys. If it's just variations, seems not worth it.

**Comment by jcushman** [comment]
Thanks! We don't specifically need a release, since we can always rely on a github .zip requirement. 🤷‍♂️

I'll open a separate issue about alphabetizing / linting.

**Comment by mlissner** [comment]
Sounds great. I think if you ever need a release you can tag a commit and update setup.py and that should cut a release when it gets merged.

**Pull request merged**
